### ISSUE TITLE
Previous / Next Article function won't work

### ISSUE THREAD

**Issue by guime7000** [ParitoshBh/grav-coder#31]
Hi !

Thanks for the work on grav-coder, I really like the sobriety of your theme !

Don't know if this should be a PR or if it's an issue due to a misconfiguration or misunderstanding of how the theme is working....

I've been in trouble to make the previous / next Article function work. Related links were always corresponding to the current article URL. I'm using Grav v1.7.38.

I managed to get it work modifying the file `navigation.html.twig` in  `/grav-coder/templates/partials/item/`

I replaced `page.prevSibling().slug (resp. nextSibling)`

with `page.parent().children().prevSibling(page.path).url (resp. nextSibling)`

and...tadam, it worked....

**Comment by ParitoshBh** [comment]
Pagination logic is already there in the theme itself. You shouldn't have needed to make the changes you made.

Can you please confirm if,
1. you've followed the instructions as mentioned under [Blog (Listing) Setup](https://github.com/ParitoshBh/grav-coder#blog-listing-setup)?
2. you've updated `grav-coder.yaml` to include following config,
```yml
post:
  navigation: true
```

**Comment by guime7000** [comment]
Hi !

My directory and file structure is :
```
mygrav/
└── grav-admin/
    └── user/
        └── pages/
            ├── 01.blog/
            │   ├── 02.dir1/
            │   │   └── item.md
            │   ├── 03.dir2/
            │   │   └── item.md
            │   ├── 04.dir3/
            │   │   └── item.md
            │   └── blog.md
            └── 02.Typography
```

Inside `01.blog` directory, my `blog.md ` contains :
```
---
 content:
     items: '@self.children'
     order:
         by: date
         dir: desc
     limit: 10
     pagination: true
 metadata:
   description: 'Some description for metadata'
 ---
```

and my `grav-coder.yaml` file inside `mygrav//grav-admin/user/themes/grav-coder/` contains :
```
enabled: true
dropdown:
  enabled: true
navbar:
  title: MyTitle
#  url: https:/myurl/blog
#  rel: me
  auth_link:
    enabled: false
    login_slug: login
    login_label: Login
#footer:
#  copyright: Grav Coder

social:
  github:
    title: Github
    url: https://mygithubURL
    icon: fab fa-github
    rel: me
  linkedin:
    title: LinkedIn
    url: https:/myLinkedInURL
    icon: fab fa-linkedin-in
    rel: me
post:
  navigation: true
  taxonomy: true
#listing_title:
#  taxonomy:
#    category: 'Category: '
#    tag: 'Tag: '
#  blogs: 'Posts'
pages:
  order:
    by: default
    dir: asc

pagination:
  count: 10
```

So where could be my mistake(s) ?
